# Generated by Django 3.2.9 on 2021-11-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
