# Generated by Django 3.2.9 on 2021-11-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_alter_usercode_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
