# Generated by Django 3.2.9 on 2021-11-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_remove_usercode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
