# Generated by Django 3.2.9 on 2021-11-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0009_auto_20211128_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharecode',
            old_name='slug',
            new_name='uniqueShareUrl',
        ),
    ]
